### ISSUE TITLE
How can i request the api for getting all the job details of a particular company

### ISSUE THREAD

**Issue by ksmvsn** [muschellij2/glassdoor#1]
i want to search the all the  job details of a particular company and  get the technology list from the results

**Comment by muschellij2** [comment]
Is that available through the API?  I don't believe it is.

See the documentation for what the API returns:
https://www.glassdoor.com/developer/companiesApiActions.htm

John

**Comment by ksmvsn** [comment]
so how do i get the job details. 
will glassdoor provide access to Job details in the future through api or
are there any paid options

**Comment by muschellij2** [comment]
These are questions for Glassdoor, not here.

As per https://www.glassdoor.com/developer/index.htm
> Unless otherwise noted, these APIs are available for public use with a free Glassdoor account and pending a short approval process. The APIs that are not provided publicly are available to our API partners. If you're interested in becoming an API partner, please contact us.

Closing issue
