### ISSUE TITLE
glassdoor api function does not support 'reviews' action call

### ISSUE THREAD

**Issue by jhsuss** [muschellij2/glassdoor#2]
I'm trying to retrieve employee reviews for specific firms using their glassdoor employer IDs. The glassdoor api documentation (https://www.glassdoor.com/developer/index.htm) and the documentation for gd_api function for this package suggest that you can do this by setting the _action_ argument = reviews and the _other_ argument = the employer ID. However, when I do this I get a 404 error:
**Error in if (!gd_success) { : argument is of length zero
In addition: Warning message:
In gd_api(action = "reviews", other = "3456", version = 1, format = "json") :
  Not Found (HTTP 404).**

From the glassdoor developer index: 
**action | The particular API call that you would like to make - see jobs, reviews, salaries, etc. sub-sections for details 
other | Each API action will require different parameters - in the example above, an employerId is passed in order to retrieve reviews.**

And from the ?gd_api documentation: 
**action	The particular API call that you would like to make
other	Each API action will require different parameters For example, an employerId is passed in order to retrieve reviews.**

**Comment by muschellij2** [comment]
I have added some capabilities, but I only believe you have access to the reviews if you are a partner of Glassdoor and have an API key that has these permissions.

Please reinstall from the github version and run:
```r
res = gd_review(employer_id = 715) # walmart
```
and see if you get anything other than a 403 - which indicates you don't have access to these.

**Comment by jhsuss** [comment]
Thanks, have tried this but am getting a 403. I guess the glassdoor public api used to allow access to reviews given the documentation but this has changed? I'll get in touch with them to see how to become a partner.
