### ISSUE TITLE
Issues with Glassdoor API 

### ISSUE THREAD

**Issue by Mahesh9849** [muschellij2/glassdoor#3]
i tried to access glass door reviews with R but i could'nt..reason being no access to api ..Could you suggest me is there a way out to access..i am working on project with glass door reviews.

**Comment by muschellij2** [comment]
You must create an API key here: https://www.glassdoor.com/developer/index.htm.  

> The APIs that are not provided publicly are available to our API partners. If you're interested in becoming an API partner, please contact us.
